#!/bin/bash

USERID=$(id -u)
if [ $USERID -eq 0 ] 
 then
    echo "You are running with user access"
 else
   echo "error : Run the script with user access"   
   exit 1
fi

VALIDATE(){
    if [ $1 -eq 0 ]
     then
     echo "Installing $2 is success"
     else
     echo "Installing $2 is Failure"
     exit 1
    fi
}

dnf list installed mysql
if [ $? -ne 0 ]
 then
  echo " Mysql is not installed ..going to install"
  dnf install mysql
  VALIDATE $? "Mysql"
 else
  echo " mysql is alread installed , nothing to do"
fi

dnf list installed python3
if [ $? -ne 0 ]
 then
 echo " python3 is not installed .. going to install"
 dnf install python3
 VALIDATE $? "python3"
 else 
 echo "python3 is already installed ...nothing to do"
fi

dnf list installed nginx
if [ $? -ne 0 ]
 then
 echo "nginx is not installed...going to install"
 dnf install nginx
 VALIDATE $? "nginx"
 else
 echo "nginx is already installed ...nothing to do"
fi